import {fresh,clone,normalizeState} from './core.js';
const WAIT_MS=10000;
const stalled=()=>Error('本地保存等待过久。请关闭其他进展页面后重试；不要清除网站数据。');
function database(){return new Promise((resolve,reject)=>{let expired=false;const req=indexedDB.open('jinzhan-web',1);const timer=setTimeout(()=>{expired=true;reject(stalled());},WAIT_MS);req.onupgradeneeded=()=>req.result.createObjectStore('state');req.onsuccess=()=>{clearTimeout(timer);if(expired){req.result.close();return;}resolve(req.result);};req.onerror=()=>{clearTimeout(timer);reject(Error('无法打开本地数据，请勿使用禁止存储的浏览模式'));};});}
// Close connections after each operation; idle background pages need none.
async function transaction(mode,run){const db=await database();return new Promise((resolve,reject)=>{let result,failure,settled=false;const tx=db.transaction('state',mode);const finish=error=>{if(settled)return;settled=true;clearTimeout(timer);db.close();error?reject(error):resolve(result);};const timer=setTimeout(()=>{failure=stalled();try{tx.abort();}catch{}finish(failure);},WAIT_MS);tx.oncomplete=()=>finish();tx.onabort=tx.onerror=()=>finish(failure||tx.error||Error('保存未完成，原文和候选仍可重试'));const req=tx.objectStore('state').get('main');req.onsuccess=()=>{try{result=run(req.result,tx.objectStore('state'));}catch(e){failure=e;tx.abort();}};});}
export function readState(){return transaction('readonly',value=>normalizeState(clone(value||fresh())));}
export function mutate(reducer){return transaction('readwrite',(value,store)=>{const next=normalizeState(clone(value||fresh()));const result=reducer(next);if(result instanceof Promise)throw Error('保存操作必须同步');next.revision=(next.revision||0)+1;store.put(next,'main');return {state:next,result};});}
export async function replaceState(next){return mutate(s=>{const revision=s.revision;for(const k of Object.keys(s))delete s[k];Object.assign(s,clone(next),{revision});});}
